### ISSUE TITLE
Fix Update Groupname

### ISSUE THREAD

**Issue by yclim** [yclim/gem#100]
Currently when group name is updated, we can't add rules to the group and backend is not updated.

**Comment by neojunjie** [comment]
I dont face this problem at my branch. Able to share how you encountered the issue?

**Comment by yclim** [comment]
how i replicate the issue:
1) create  a new  group
2) click on the group name to edit it  (e.g  change 'unititled-1'  to 'abc')
3) try to  add  a rule to  abc

 @shaojieyew is working on #111, can hold this for  awhile

**Comment by neojunjie** [comment]
It affects not just updating of the group name. Delete group is also affected.
1) Create new group
2) Click on "X" to delete the group.
3) The ui will not refresh the change but the backend already persisted the change.

i think it is related to focusgrp.  If i comment both focusGrp and setFocusGrp @ Grouplist.tsx (line 54 and 55) then I can add rules to the group.

**Comment by neojunjie** [comment]
got it solved.

Need to set group.name = input.newGroupName first before returning the map (EditGroup.tsx)
