### ISSUE TITLE
Add groupid in Group

### ISSUE THREAD

**Issue by shaojieyew** [yclim/gem#111]
Change the group identifier to groupid

**Comment by yclim** [comment]
we still want the group name to be unique though.

**Comment by shaojieyew** [comment]
> we still want the group name to be unique though.

Ok, noted. I guess i will still continue with this, to decouple renaming function from other implementation?

**Comment by yclim** [comment]
> > we still want the group name to be unique though.
> 
> Ok, noted. I guess i will still continue with this, to decouple renaming function from other implementation?

👍
