### ISSUE TITLE
Classes for Extract page

### ISSUE THREAD

**Issue by yclim** [yclim/gem#137]
**Scope**: Implement `ExtractConfig`, `AbstractExtractor`, `TimestampColumn`, `ExtractService`, `ExtractController`, `iExtractDAO` classes

Each group contains one optional `ExtractConfig`. It contains
- table name
- one-to-many Column Names
- one `AbstractExtractor`
- zero-to-many `TimestampColumn`

`AbstractExtractor` allows implementation of Extractors to extract structured record from GEMFile. 
Extractor contains 
- one-to-many parameters
- `extract(gemFile: GEMFILe): List<List<String>>`

`TimestampColumn` can be use to transform a column containing date information into a common date format (e.g ISO format - 2020-04-01 12:00Z). The final output provided by `ExtractService` append converted timestamp values with data extracted from AbstractExtractor. `TimestampColumn` have
- columnName: pointing to one of `ExtractConfig`'s column
- newColumnName: new column name for this timestamp column
- timezone information. Should use somewhere where java `ZoneId` could recognize.
- datePattern: the date format of column name base on java [SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html)
- `convert(string): string`: converts a date string using datePattern into ISO date format including timezone(e.g 2020-04-01 12:00Z)

`ExtractService` use extracts data from GemFile. It provides:
- `extractData(ExtractConfig config, GemFile file): List<List<String>>` : return data should include data from both `AbstractExtractor` and `TimestampColumn` conversion. This method should be stateless and idempotent', i.e - should not be back by HashMap or writes to a HashMap. It simplify extract data from gemFile. This method will be use in 'routine flow' to extract data from GemFile without the dependency on backing stores`
- `extractAndStoreData(groupId: string): Map<String, List<List<String>>`: extract table data from all files in group. Map key refers to File_Id (i.e absolute file path), and value refers to extracted table data from that GemFile
- `getExtractedData(groupId: string):Map<String, List<List<String>>`  return extracted data from backing store

`ExtractController` provides endpoint for UI:
- `extract(groupId: string): List<{filename: string, count: number}>` : performs extraction and return all filename in group with it's record count. 
- `getFilesCount(groupId: string) List<{filename: string, count: number}>`: return all filename in group with it's record count
- `getExtractedRecords(groupId: string, file Id: string): List<List<String>>`:  given groupId and file id, return extracted data
- `updateExtractConfig(groupId: string, ExtractConfig)`

**NOT in scope:** 
- ExtractService of should be in-memory (HashMap base). RocksDB implementation could come as a separate issue later if needed.

Implementation Notes: Since it's quite a big issue, prefer to break down the implementation into multiple PR. E.g break down into 4 PR:
- Scaffolding for all Extract Page classes (entities) without implementations
- ExtractService without TimestampColumn implementation + test cases only
- TimestampColumn implementation only + test cases only
- ExtractController only

@neojunjie @onegang @metamagpie @shaojieyew @orhlulu: questions/comment welcome!

**Comment by onegang** [comment]
@yclim What's the diff between REST methods `extract(groupId: string): List<{filename: string, count: number}>` and `getFilesCount(groupId: string) List<{filename: string, count: number}>`?

**Comment by yclim** [comment]
> @yclim What's the diff between REST methods `extract(groupId: string): List<{filename: string, count: number}>` and `getFilesCount(groupId: string) List<{filename: string, count: number}>`?

extract = extract and return the extracted data.
 getFilesCount = returns the extracted data from cache (or rocksdb). I'm thinking to use this to populate the filecount table quickly when switch around tabs and pages and populate the group extract count tag

![image](https://user-images.githubusercontent.com/4500007/81572152-6f216c80-93d5-11ea-97b9-8b29e6eeaaa5.png)

**Comment by onegang** [comment]
> > @yclim What's the diff between REST methods `extract(groupId: string): List<{filename: string, count: number}>` and `getFilesCount(groupId: string) List<{filename: string, count: number}>`?
> 
> extract(): extract and return the extracted data.
> getFilesCount(): returns the extracted data from cache (or rocksdb). I'm thinking to use this to populate the filecount table quickly when switch around tabs and pages and populate the group extract count tag
> 
> ![image](https://user-images.githubusercontent.com/4500007/81572152-6f216c80-93d5-11ea-97b9-8b29e6eeaaa5.png)

Got it!
