### ISSUE TITLE
Scaffolding for all Extract Page classes without implementations

### ISSUE THREAD

**Issue by yclim** [yclim/gem#143]
reference #137

**Comment by orhlulu** [comment]
i try this one.. may need more info later

**Comment by orhlulu** [comment]
@yclim 

> AbstractExtractor allows implementation of Extractors to extract structured record from GEMFile.
> Extractor contains
> 
> one-to-many parameters
> extract(gemFile: GEMFILe): List<List<String>>

1) Does this means we going to have 1 csvExtractor, 1 excelExtractor and 1 pdfExtract which inherit AbstractExtractor?
2) For the one-to-many parameter what the parameter be used for?

**Comment by orhlulu** [comment]
i create some simple classes are these wat you all looking for?
