### ISSUE TITLE
Implement Tika Content Regex Extractor and unit test

### ISSUE THREAD

**Issue by onegang** [yclim/gem#173]

**Comment by orhlulu** [comment]
@onegang @yclim for pdfextractor, do we extract only content of the PDF only or together with metadata? And for the extractConfig, do we need another List<String> for content matches?

**Comment by yclim** [comment]
we extract pdf to tika content. so i think we should implement Tika Content Regex extractor instead

**Comment by yclim** [comment]
Tika content regex extractor should be able to extract more than one record from tika content
e.g given this tika content
```
cust1 orhlulu 123
cust2 onegang 321
```
and regex with 3 capture group
```
(\w+)\s+(\w+)\s(\d+)
```
regex extractor should return 2 records. can try use regex101.com to try it out

**Comment by orhlulu** [comment]
Under the Tikacontentextractor, it takes 1 param which will be the regex string

But for the extractConfig, what should we pass into it? the regex string also?

**Comment by orhlulu** [comment]
create a rough implementation of the tikacontent extraction..
