### ISSUE TITLE
remove logic that generates file in ExcelExtractorTest ExcelFeatureTest testcase

### ISSUE THREAD

**Issue by yclim** [yclim/gem#186]
how to reproduce

1. run ExcelExtractorTest and ExcelFeatureTest
2. notice manual_cars_0.xlsx and manual_cars.xlsx is generated in `src/test/resources`

**Comment by orhlulu** [comment]
i try running the 2 tests.. no files created..
the 2 files should be checked in.. instead of self created..

**Comment by yclim** [comment]
try rollback the code in `test/java` . your test file should be black in color, which means no changes
![image](https://user-images.githubusercontent.com/4500007/82509847-a1506e00-9b3b-11ea-8359-37556e5d8782.png)
after you run test, and they become blue, which means the test generate new file to replace.
![image](https://user-images.githubusercontent.com/4500007/82509987-01dfab00-9b3c-11ea-84f0-14ec442896b6.png)


it happens for excel test only

**Comment by onegang** [comment]
POI will change the modified time, open the file in readonly mode will prevent the file from changing.
