### ISSUE TITLE
Load up mock data

### ISSUE THREAD

**Issue by onegang** [yclim/gem#2]
How about loading in some mock data files for the unit test and for our app dev?

**Comment by yclim** [comment]
this will be very useful, i'm thinking just store them in git repo for simplicity? set one folder to keep all our mock files?

**Comment by onegang** [comment]
> this will be very useful, i'm thinking just store them in git repo for simplicity? set one folder to keep all our mock files?

yes, would be good

**Comment by yclim** [comment]
build file generators instead so that we could have lots of mock files
