### ISSUE TITLE
CI/CD: Jenkins

### ISSUE THREAD

**Issue by onegang** [yclim/gem#4]
Fund a tiny jenkins instance at aws?

**Comment by onegang** [comment]
@all Have a basic Jenkins running: https://tinyurl.com/s6qedgn. Plugin is still in a mess as jenkins mirror has issues in the afternoon.

**Comment by onegang** [comment]
Previos instance bombed... use this: https://tinyurl.com/wojwtj3

**Comment by yclim** [comment]
nice. maybe change the password and share in chat group instead since it's a public repo :D

**Comment by onegang** [comment]
Oh damn I forgot this is a public repo!
