### ISSUE TITLE
integrate jenkin's build status with github pull request

### ISSUE THREAD

**Issue by yclim** [yclim/gem#48]

**Comment by onegang** [comment]
Haha, Current Jenkins cannot run... I am too cheapskate to bump up the Jenkins instance... still running micro, 1GB memory fails when it spin off the node yarn process... will look up upgrading to small instance... then will hook it up to this github

**Comment by yclim** [comment]
thanks! we will all share the bill.

**Comment by onegang** [comment]
test

**Comment by onegang** [comment]
@yclim Ok, configured jenkins pull request. Can see the effect here: https://github.com/yclim/gem/pull/66

But currently it is running cron-polling mode (i.e. jenkins check github every 5mins). That is, there will be a delay before the pull request shows this check... to confiure it on push mode, we need admin rights to configure the webhook.

**Comment by yclim** [comment]
cool. can't find a way to give collaborator admin rights. maybe i can try doing that.
