### ISSUE TITLE
Design Classes for Rule, Parameters and Group 

### ISSUE THREAD

**Issue by yclim** [yclim/gem#60]
**Rule** class  should be a abstract class to allow implementer to add new rules to GEM. Abstract rule should allow the definition of
- rule name, rule type (rules with the same type will be displayed together in UI (e.g csv, excel, tika) 
- one-to-many parameters needed by the rule (can assume all string type for simplicity first?)
- each parameter should have label, and placeholder (for UI use)
- each parameter have a type (e.g regex, string, int) to help UI to determine which input component to use 
 to capture the input
- **check(gemFile:  [GEMFile](https://github.com/yclim/gem/blob/master/src/main/java/innohack/gem/entity/GEMFile.java)): Boolean** function

**Group** class contains zero-to-many more rule instances (just the parameter values and reference to the rule)
- matchedCount: Number of GEMFile that matched this rule
- zero to many reference to GEMFile?

**Calculating the matchedCount for each  Group**
I'm imaging the way to calculate matchedCount for each group is derived from a 'Truth Table' which is the boolean result cache of all combination of Rule instances and GemFile. Whenever a rule is added (no matter which group it is added to),  we check all  GemFile against the rule instance (using check function) and update the boolean result to the 'Truth Table'.

Truth table Data structure could be  `Map<String, Map<String, Boolean>>`, where 
-  the first String is GemFile id, 
- the second String is the Rule Instance Id, 
- and Boolean is the result of the checking the  GemFile with the rule.

`matchedCount` for each group can then be 'queried' from this 'Truth Table'. 
Since it's constant time to check the boolean result when given a Gem File and Rule Instance with HashMap, the time complexity  of calculating matchCount for a given group is
`O(g *  f) `,  where
`g`  is the number of rule instances in the given group
`f` is total number of GemFiles
given number of gem file files  < 1000 and  say number of rules < 50, this should be quite feasible

**Adding or updating new rule instance**
When we add new rule instance to a group,  we update the 'Truth Table'.  The time complexity of adding new rule instance is:
`O (f * c)` where 
`f`  is the number of  Gem Files
`c`  is the cost of using it's Rule.check function.

When we update a rule, we first delete all entries in the truth table associated with the rule instance. The time complexity to delete an entry is: `O(n * f)` where n is the total num of rule instances

Once truth table change, (add, update, delete  of rule instance), we should calculate matchCount again for each group

**Calculating count of file that does not belong to any group**
It is equivalent of saying which GemFile in the truth table has all rule instances result == false
The time complexity of calculating this is `O(n * f)`

@neojunjie,  @onegang , @metamagpie,  @shaojieyew,  @orhlulu :  comments / ideas are very 
 welcome!

**Comment by shaojieyew** [comment]
I think its good, most of the scenarios in matching and grouping are captured. I have some points to add on from there
1. We might need a Value field in Parameter Class to capture the value entered by the user.
2. For calculating matchedCount, I think we could further improve the performance of matchedCount by storing just Map<String, String>. By keeping only the matched FileId/GroupId in the truth table, we can make use of map.size for calculating matched count which has almost O(1) of complexity.

**Comment by yclim** [comment]
> I think its good, most of the scenarios in matching and grouping are captured. I have some points to add on from there
> 
> 1. We might need a Value field in Parameter Class to capture the value entered by the user.
> 2. For calculating matchedCount, I think we could further improve the performance of matchedCount by storing just Map<String, String>. By keeping only the matched FileId/GroupId in the truth table, we can make use of map.size for calculating matched count which has almost O(1) of complexity.

1. Yeap we need that!
2. Interesting point. For the Map<String, String>, are you thinking of `File Id -> Group Id` or `Group Id -> File Id` ?

**Comment by shaojieyew** [comment]
> > I think its good, most of the scenarios in matching and grouping are captured. I have some points to add on from there
> > 
> > 1. We might need a Value field in Parameter Class to capture the value entered by the user.
> > 2. For calculating matchedCount, I think we could further improve the performance of matchedCount by storing just Map<String, String>. By keeping only the matched FileId/GroupId in the truth table, we can make use of map.size for calculating matched count which has almost O(1) of complexity.
> 
> 1. Yeap we need that!
> 2. Interesting point. For the Map<String, String>, are you thinking of `File Id -> Group Id` or `Group Id -> File Id` ?

Ops, theres a typo, suppose to be Map<String, List<String>> where `File Id -> List of matching Group Id`. So that we can store all the files as key and for each file will have a list of groups that match it.

**Comment by yclim** [comment]
> Ops, theres a typo, suppose to be `Map<String, List<String>>` where `File Id -> List of matching Group Id`. So that we can store all the files as key and for each file will have a list of groups that match it.

I think the rationale of using `Map<String, Map<String, String>>`  i.e  `File Id  -> Rule Instance Id ->   Boolean`
is such that we can minimize the cost of running `Rule.check(gemFile)`  which is the most uncontrollable part  of in our system (e.g running regex on a 50mb file). Ideally we should only run once for each rule instance and each file. This 'truth' table will keep the result of all run. It does not give information quickly (for e.g matchCount need `O(g * f)`  instead of `O(1)`), but it make sure that `check` is run only once.

I think your suggestion `File  Id -> List  of matching Group Id`  could be an index view we can build from the truth table to speed up matchedCount calculation performance. But `O(g * f)` does not look too bad on theory yet?
