### ISSUE TITLE
How to extract metadata and content using Tika?

### ISSUE THREAD

**Issue by yclim** [yclim/gem#7]
write example code in: innohack.gem.example package

**Comment by orhlulu** [comment]
out of box tika runnable provides the following:

![tika_meta](https://user-images.githubusercontent.com/63329580/78867200-4c690480-7a73-11ea-9c39-1b69a185383d.png)

filename: resourcename
content length: size
content type: zip or MS documents

Will try and see to incorporate to stand alone java program
