### ISSUE TITLE
Feature store exploration

### ISSUE THREAD

**Issue by yclim** [yclim/gem#8]
Given we allow user to work on 1000 samples files max, 
- We need a feature store to store all data extracted from Feature Extractors (maybe in GBs?) and allow them to be retrieved efficiently. 
- Feature data is key value in nature
- Data should be stored in a way such that given a filename, we could retrieve all feature values of that file efficiently (e.g partition by file)
- We also need it to be portable (no software installation!)

**Comment by neojunjie** [comment]
will be evaluating rocksdb as potential candidate for our feature store

**Comment by neojunjie** [comment]
Seem like rocksdb can fit our requirements quite well.

1. We need a feature store to store all data extracted from Feature Extractors (maybe in GBs?) and allow them to be retrieved efficiently.   (maximum recommended sizes for key and value are 8MB and 3GB)
2. Feature data is key value in nature (key value store)
3. Data should be stored in a way such that given a filename, we could retrieve all feature values of that file efficiently (e.g partition by file) (prefix scan, boom filter and memtable aka  caching)
4. We also need it to be portable (yes)
