### ISSUE TITLE
Try out Travis

### ISSUE THREAD

**Issue by onegang** [yclim/gem#88]
This is to try out Travis (most popular CI for Github), which should be much easier (than Jenkins)... and is free! (Saves us $30sgd per month!) It easily gives us the commit and pr web hooks, and we could easily add the build status banner to our Readme too!

**Comment by onegang** [comment]
@yclim I may need you to do a few steps (when you are free):
- login to Travis: [https://travis-ci.org/](https://travis-ci.org/) (Use your github account)
- enable this repository in your Travis page (which will setup the webhooks in github)
- after these steps, I will continue to configure it from there using my Travis account. (it is mainly configured by .travis.yml file, similar to jenkins pipeline file)

**Comment by yclim** [comment]
Nice. its done. i can see travis in webhooks now
