### ISSUE TITLE
Fix Update Group Name feature

### ISSUE THREAD

**Issue by yclim** [yclim/gem#94]
currently when group name is updated, it was updated in frontend only. Fix it to persist change to backend hashMap

**Comment by neojunjie** [comment]
It is possible that the group name is not unique. What will be the expected behaviour then?
Do we flag user for duplicate name in the ui or allow user to enter same group name?

**Comment by shaojieyew** [comment]
Maybe we could introduce a groupId? If groupid is provided during api call on saving the group, backend will update the group else it will create a new group?

**Comment by neojunjie** [comment]
Yup, i think we should add a group id. 
I think there is 1 issue that can keep track of it (issue 60 design classes for group, rule etc)
